model: "allenai/OLMo-2-0425-1B"
tokenizer: "allenai/OLMo-2-0425-1B"
prompt_type: "r1_zero"
infer_device: 6
train_device: cuda:7
gradient_accumulation_steps: 32
max_grad_norm: 1.0
top_p: 1.0
baseline: "mean"
advantage_eps: 0.000001
advantage_normalizer: "std"
importance_reweighting_method: "none"
n_train_examples: 6400
n_val_examples: 1024
eval_interval: 10
num_rollout_steps: 200
learning_rate: 1e-5
rollout_batch_size: 256
train_batch_size: 256
group_size: 8
sampling_temperature: 1.0
sampling_max_tokens: 512
gpu_memory_utilization: 0.9